#!/usr/bin/env node
/**
 * @fileoverview liferay-sdk-cli — Generate a static SDK from Liferay OpenAPI specs.
 *
 * Usage:
 *   npx liferay-sdk-cli generate \
 *     --baseUrl https://your-liferay.com \
 *     --output ./generated-sdk \
 *     [--username test@liferay.com --password test] \
 *     [--swagger /o/headless-delivery/v1.0/openapi.json,/o/headless-admin-user/v1.0/openapi.json]
 */

import { parseArgs } from 'node:util';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';

// ─── CLI Argument Parsing ──────────────────────────────────────────────────

const { values: args } = parseArgs({
  allowPositionals: true,
  options: {
    baseUrl:  { type: 'string' },
    output:   { type: 'string', default: './generated-sdk' },
    username: { type: 'string' },
    password: { type: 'string' },
    token:    { type: 'string' },
    swagger:  { type: 'string' },
    help:     { type: 'boolean', short: 'h', default: false },
  },
});

const [command] = process.argv.slice(2);

if (args.help || command !== 'generate') {
  console.log(`
liferay-sdk-cli — Liferay Headless SDK generator

Usage:
  npx liferay-sdk-cli generate [options]

Options:
  --baseUrl    <url>    (required) Base URL of your Liferay instance
  --output     <dir>   Output directory (default: ./generated-sdk)
  --username   <str>   Username for Basic Auth
  --password   <str>   Password for Basic Auth
  --token      <str>   OAuth2 Bearer token
  --swagger    <urls>  Comma-separated list of OpenAPI endpoint paths
                       Default: /o/headless-delivery/v1.0/openapi.json,
                                /o/headless-admin-user/v1.0/openapi.json,
                                /o/headless-admin-content/v1.0/openapi.json,
                                /o/object-admin/v1.0/openapi.json

Examples:
  npx liferay-sdk-cli generate --baseUrl https://liferay.example.com --output ./sdk
  npx liferay-sdk-cli generate --baseUrl https://liferay.example.com \\
    --username test@liferay.com --password test \\
    --swagger /o/headless-delivery/v1.0/openapi.json
`);
  process.exit(0);
}

if (!args.baseUrl) {
  console.error('[liferay-sdk-cli] Error: --baseUrl is required.');
  process.exit(1);
}

// ─── Default Swagger Endpoints ─────────────────────────────────────────────

const DEFAULT_SWAGGER_URLS = [
  '/o/headless-delivery/v1.0/openapi.json',
  '/o/headless-admin-user/v1.0/openapi.json',
  '/o/headless-admin-content/v1.0/openapi.json',
  '/o/object-admin/v1.0/openapi.json',
];

const swaggerUrls = args.swagger
  ? args.swagger.split(',').map((s) => s.trim())
  : DEFAULT_SWAGGER_URLS;

const baseUrl = args.baseUrl.replace(/\/$/, '');
const outputDir = resolve(process.cwd(), args.output);

// ─── Auth Header ───────────────────────────────────────────────────────────

function buildAuthHeader() {
  if (args.token) return `Bearer ${args.token}`;
  if (args.username && args.password) {
    const encoded = Buffer.from(`${args.username}:${args.password}`).toString('base64');
    return `Basic ${encoded}`;
  }
  return null;
}

// ─── Fetch Helper ──────────────────────────────────────────────────────────

async function fetchSchema(url) {
  const authHeader = buildAuthHeader();
  const headers = { Accept: 'application/json' };
  if (authHeader) headers['Authorization'] = authHeader;

  const response = await fetch(url, { headers });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} fetching ${url}`);
  }
  return response.json();
}

// ─── Code Generation ───────────────────────────────────────────────────────

/**
 * Converts an operationId to camelCase.
 * @param {string} id
 */
function toCamel(id) {
  return id
    .replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (c) => c.toLowerCase());
}

/**
 * Converts a tag to a JS property name.
 * @param {string} tag
 */
function toProperty(tag) {
  return tag
    .replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (c) => c.toLowerCase())
    .replace(/[^a-zA-Z0-9_$]/g, '');
}

/**
 * Generates a static JS service module file from an OpenAPI schema.
 * @param {object} schema
 * @param {string} moduleName
 * @returns {string}
 */
function generateServiceFile(schema, moduleName) {
  const paths = schema.paths || {};
  const tagGroups = {};

  for (const [path, pathItem] of Object.entries(paths)) {
    for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
      const op = pathItem[method];
      if (!op) continue;
      const tag = toProperty((op.tags && op.tags[0]) || 'default');
      if (!tagGroups[tag]) tagGroups[tag] = [];
      tagGroups[tag].push({ method, path, op });
    }
  }

  const lines = [
    `/**`,
    ` * Auto-generated service module: ${moduleName}`,
    ` * Generated by liferay-sdk-cli on ${new Date().toISOString()}`,
    ` * DO NOT EDIT — regenerate with: npx liferay-sdk-cli generate`,
    ` */`,
    ``,
    `import { LiferayHeadlessClient } from '../index.js';`,
    ``,
  ];

  for (const [tag, ops] of Object.entries(tagGroups)) {
    lines.push(`export const ${tag} = (client) => ({`);
    for (const { method, path, op } of ops) {
      if (!op.operationId) continue;
      const methodName = toCamel(op.operationId);
      const summary = op.summary ? `  /** ${op.summary} */` : '';
      if (summary) lines.push(summary);
      lines.push(`  async ${methodName}(params = {}) {`);
      lines.push(`    const { body, headers, ...rest } = params;`);

      // Path params
      const pathParams = (op.parameters || []).filter((p) => p.in === 'path').map((p) => p.name);
      if (pathParams.length > 0) {
        lines.push(`    let url = \`${path.replace(/\{(\w+)\}/g, '${encodeURIComponent(rest.$1 ?? "")}')}\`;`);
        for (const p of pathParams) {
          lines.push(`    delete rest.${p};`);
        }
      } else {
        lines.push(`    const url = '${path}';`);
      }

      lines.push(`    return client.request({ method: '${method.toUpperCase()}', path: url, query: rest, body, headers });`);
      lines.push(`  },`);
    }
    lines.push(`});`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  console.log(`[liferay-sdk-cli] Generating SDK for ${baseUrl}`);
  console.log(`[liferay-sdk-cli] Output directory: ${outputDir}`);

  await mkdir(outputDir, { recursive: true });
  await mkdir(join(outputDir, 'services'), { recursive: true });

  const generatedModules = [];

  for (const schemaUrl of swaggerUrls) {
    const absoluteUrl = schemaUrl.startsWith('http') ? schemaUrl : `${baseUrl}${schemaUrl}`;
    console.log(`[liferay-sdk-cli] Loading: ${absoluteUrl}`);

    let schema;
    try {
      schema = await fetchSchema(absoluteUrl);
    } catch (err) {
      console.warn(`[liferay-sdk-cli] Warning: Failed to load ${absoluteUrl}: ${err.message}`);
      continue;
    }

    const title = (schema.info && schema.info.title) || schemaUrl;
    const safeName = title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .toLowerCase();

    const serviceCode = generateServiceFile(schema, title);
    const filePath = join(outputDir, 'services', `${safeName}.js`);
    await writeFile(filePath, serviceCode, 'utf-8');
    console.log(`[liferay-sdk-cli] Generated: services/${safeName}.js`);
    generatedModules.push({ name: safeName, url: schemaUrl });
  }

  // Write index that re-exports all services
  const indexLines = [
    `/**`,
    ` * Auto-generated SDK index`,
    ` * Generated: ${new Date().toISOString()}`,
    ` */`,
    `export { LiferayHeadlessClient } from 'liferay-headless-sdk';`,
    `export { iteratePages, collectAllPages, getPage } from 'liferay-headless-sdk';`,
    `export { LiferayAPIError } from 'liferay-headless-sdk';`,
    ``,
    ...generatedModules.map((m) => `export * from './services/${m.name}.js';`),
  ];

  await writeFile(join(outputDir, 'index.js'), indexLines.join('\n'), 'utf-8');

  console.log(`\n[liferay-sdk-cli] ✅ Done! ${generatedModules.length} module(s) generated in ${outputDir}`);
  console.log(`\nUsage:\n  import { LiferayHeadlessClient } from '${outputDir}/index.js';\n`);
}

main().catch((err) => {
  console.error('[liferay-sdk-cli] Fatal error:', err.message);
  process.exit(1);
});
